name: py_env
channels:
  - defaults
  - conda-forge
dependencies:
  - autopep8=1.6
  - flake8=4.0
  - flake8-docstrings=1.7
  - gspread=5.7
  - isort=5.9
  - ipykernel=6.15
  - matplotlib=3.5
  - numpy=1.21
  - pandas=1.4
  - pip=21.2
  - python=3.8
  - python-dotenv=1.0
  - scikit-learn=1.0
  - scipy=1.7
  - statsmodels=0.13
  - sqlalchemy=2.0
  - pip:
      - stravalib
